# Generated by Django 6.0.1 on 2026-02-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='file_python',
            field=models.FileField(null=True, upload_to='files/', verbose_name='загрузите файл'),
        ),
    ]
