# Generated by Django 6.0.1 on 2026-02-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0003_alter_proglang_file_python'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proglang',
            name='file_python',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='загрузите файл'),
        ),
    ]
