# Generated by Django 6.0.1 on 2026-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0004_alter_proglang_file_python'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
